package niki119.slit.items.pickaxe;

import niki119.slit.materials.Materials;

public class Pickaxes {
    public static final PickaxeBase BEACON = new PickaxeBase("beacon_pickaxe", Materials.BEACON);
    public static final PickaxeBase BEDROCK = new PickaxeBase("bedrock_pickaxe", Materials.BEDROCK);
    public static final PickaxeBase BONE_BLOCK = new PickaxeBase("bone_block_pickaxe", Materials.BONE_BLOCK);
    public static final PickaxeBase BRICK = new PickaxeBase("brick_pickaxe", Materials.BRICK);
    public static final PickaxeBase CACTUS = new PickaxeBase("cactus_pickaxe", Materials.CACTUS);
    public static final PickaxeBase CAKE = new PickaxeBase("cake_pickaxe", Materials.CAKE);
    public static final PickaxeBase CHORUS = new PickaxeBase("chorus_pickaxe", Materials.CHORUS);
    public static final PickaxeBase CLAY = new PickaxeBase("clay_pickaxe", Materials.CLAY);
    public static final PickaxeBase COAL_BLOCK = new PickaxeBase("coal_block_pickaxe", Materials.COAL_BLOCK);
    public static final PickaxeBase COBBLESTONE_MOSSY = new PickaxeBase("cobblestone_mossy_pickaxe", Materials.COBBLESTONE_MOSSY);
    public static final PickaxeBase DIRT = new PickaxeBase("dirt_pickaxe", Materials.DIRT);
    public static final PickaxeBase EMERALD_BLOCK = new PickaxeBase("emerald_block_pickaxe", Materials.EMERALD_BLOCK);
    public static final PickaxeBase END_STONE = new PickaxeBase("end_stone_pickaxe", Materials.END_STONE);
    public static final PickaxeBase GLASS = new PickaxeBase("glass_pickaxe", Materials.GLASS);
    public static final PickaxeBase GLOWSTONE = new PickaxeBase("glowstone_pickaxe", Materials.GLOWSTONE);
    public static final PickaxeBase GRAVEL = new PickaxeBase("gravel_pickaxe", Materials.GRAVEL);
    public static final PickaxeBase HARDENED_CLAY = new PickaxeBase("hardened_clay_pickaxe", Materials.HARDENED_CLAY);
    public static final PickaxeBase HAY_BLOCK = new PickaxeBase("hay_block_pickaxe", Materials.HAY_BLOCK);
    public static final PickaxeBase ICE = new PickaxeBase("ice_pickaxe", Materials.ICE);
    public static final PickaxeBase LAPIS_BLOCK = new PickaxeBase("lapis_block_pickaxe", Materials.LAPIS_BLOCK);
    public static final PickaxeBase MAGMA = new PickaxeBase("magma_pickaxe", Materials.MAGMA);
    public static final PickaxeBase MELON = new PickaxeBase("melon_pickaxe", Materials.MELON);
    public static final PickaxeBase MUSHROOM_BLOCK_BROWN = new PickaxeBase("mushroom_block_brown_pickaxe", Materials.MUSHROOM_BLOCK_BROWN);
    public static final PickaxeBase MUSHROOM_BLOCK_RED = new PickaxeBase("mushroom_block_red_pickaxe", Materials.MUSHROOM_BLOCK_RED);
    public static final PickaxeBase NETHERRACK = new PickaxeBase("netherrack_pickaxe", Materials.NETHERRACK);
    public static final PickaxeBase NETHER_BRICK = new PickaxeBase("nether_brick_pickaxe", Materials.NETHER_BRICK);
    public static final PickaxeBase NOTEBLOCK = new PickaxeBase("noteblock_pickaxe", Materials.NOTEBLOCK);
    public static final PickaxeBase OBSIDIAN = new PickaxeBase("obsidian_pickaxe", Materials.OBSIDIAN);
    public static final PickaxeBase PRISMARINE_DARK = new PickaxeBase("prismarine_dark_pickaxe", Materials.PRISMARINE_DARK);
    public static final PickaxeBase PRISMARINE_ROUGH = new PickaxeBase("prismarine_rough_pickaxe", Materials.PRISMARINE_ROUGH);
    public static final PickaxeBase PUMPKIN = new PickaxeBase("pumpkin_pickaxe", Materials.PUMPKIN_SIDE);
    public static final PickaxeBase PURPUR_BLOCK = new PickaxeBase("purpur_block_pickaxe", Materials.PURPUR_BLOCK);
    public static final PickaxeBase QUARTZ_BLOCK = new PickaxeBase("quartz_block_pickaxe", Materials.QUARTZ_BLOCK);
    public static final PickaxeBase REDSTONE_BLOCK = new PickaxeBase("redstone_block_pickaxe", Materials.REDSTONE_BLOCK);
    public static final PickaxeBase RED_NETHER_BRICK = new PickaxeBase("red_nether_brick_pickaxe", Materials.RED_NETHER_BRICK);
    public static final PickaxeBase RED_SAND = new PickaxeBase("red_sand_pickaxe", Materials.RED_SAND);
    public static final PickaxeBase SAND = new PickaxeBase("sand_pickaxe", Materials.SAND);
    public static final PickaxeBase SEA_LANTERN = new PickaxeBase("sea_lantern_pickaxe", Materials.SEA_LANTERN);
    public static final PickaxeBase SLIME = new PickaxeBase("slime_pickaxe", Materials.SLIME);
    public static final PickaxeBase SNOW = new PickaxeBase("snow_pickaxe", Materials.SNOW);
    public static final PickaxeBase SOUL_SAND = new PickaxeBase("soul_sand_pickaxe", Materials.SOUL_SAND);
    public static final PickaxeBase SPONGE = new PickaxeBase("sponge_pickaxe", Materials.SPONGE);
    public static final PickaxeBase STONE = new PickaxeBase("stone_pickaxe", Materials.STONE);
    public static final PickaxeBase STONE_ANDESITE = new PickaxeBase("stone_andesite_pickaxe", Materials.STONE_ANDESITE);
    public static final PickaxeBase STONE_DIORITE = new PickaxeBase("stone_diorite_pickaxe", Materials.STONE_DIORITE);
    public static final PickaxeBase STONE_GRANITE = new PickaxeBase("stone_granite_pickaxe", Materials.STONE_GRANITE);
    public static final PickaxeBase TNT = new PickaxeBase("tnt_pickaxe", Materials.TNT);
    public static final PickaxeBase WOOL = new PickaxeBase("wool_pickaxe", Materials.WOOL);
}
